services:
  - type: web
    name: mi-api
    runtime: docker
    branch: ClienteAPI
    rootDir: ./registrotecnico
    dockerfilePath: ./registrotecnico/Dockerfile
    region: oregon
    plan: free
    autoDeploy: true
