services:
  - type: web
    name: mi-api
    runtime: docker
    branch: ClienteAPI
    rootDir: ./ClienteAPI
    dockerfilePath: ./ClienteAPI/Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
